server:
  port: 8081
spring:
  rabbitmq:
    host: 192.168.153.168
    port: 5672
    virtual-host: /zch
    username: admin
    password: 123456
    listener:
      type: simple # simple-listener容器使用一个额外线程处理消息  direct-listener（监听器）容器直接使用consumer线程
      simple:
        acknowledge-mode: manual # manual-手动  auto-自动（无异常直接确认，有异常无限重试） none-不重试
        prefetch: 1 # 能者多劳
        concurrency: 3 # 避免消息堆积，初始化多个消费者线程
